version: '3'
services:
 web:
  stdin_open: true # docker run -i
  tty: true        # docker run -t
  build: 
   context: .
   dockerfile: Dockerfile.dev
  ports: 
   - "80:3000"
  volumes:
   - .:/app

